### ISSUE TITLE
Perturbation csv output

### ISSUE THREAD

**Issue by hanhuajun40** [velten-group/crispat#1]
Hi, Jana,

Thanks for your nice work to systematically compare different guide assignment methods. I am curious whether you can add extra column to show the UMI for each guide per cell in the perturbations.csv, or like 10x protospacer_calls_per_cell.csv output, which contains cell barcode, num_features, feature_calls, and UMI. UMI info will be very useful for further filtering. Thanks so much. 

Yours sincerely,
Huajun

**Comment by JanaBraunger** [comment]
Hi Huajun,

thanks a lot for your feedback. I have added a 'UMI_counts' column to the outputs of all our guide assignment methods which contains the UMI counts of an assigned gRNA in a cell. I just pushed this update as a new version (0.9.3). The 'perturbations.csv' files are now called 'assignments.csv' for more clarity.  

Best regards,
Jana
